### ISSUE TITLE
Project not building with gcc 7+

### ISSUE THREAD

**Issue by asherzhou** [ucbrise/confluo#119] opened 2018-12-30 06:56 UTC
I had a issues regarding the compilation of compiling this version using GCC 7 +.

**Comment by asherzhou** [comment] 2018-12-30 06:59
On the Linux  Using GCC 7.3.1.


```
In file included from /data1/asherzhou/confluo-single-machine/libconfluo/src/threads/periodic_task.cc:1:0:
/data1/asherzhou/confluo-single-machine/libconfluo/confluo/threads/periodic_task.h:42:19: error: 'std::function' has not been declared
   bool start(std::function<void(void)> task, uint64_t interval_ms = 1);
                   ^~~~~~~~
/data1/asherzhou/confluo-single-machine/libconfluo/confluo/threads/periodic_task.h:42:27: error: expected ',' or '...' before '<' token
   bool start(std::function<void(void)> task, uint64_t interval_ms = 1);
                           ^
/data1/asherzhou/confluo-single-machine/libconfluo/src/threads/periodic_task.cc:25:32: error: 'bool periodic_task::start' is not a static data member of 'class periodic_task'
 bool periodic_task::start(std::function<void(void)> task, uint64_t interval_ms) {
                                ^~~~~~~~
/data1/asherzhou/confluo-single-machine/libconfluo/src/threads/periodic_task.cc:25:32: error: 'function' is not a member of 'std'
/data1/asherzhou/confluo-single-machine/libconfluo/src/threads/periodic_task.cc:25:32: note: suggested alternative: 'is_function'
 bool periodic_task::start(std::function<void(void)> task, uint64_t interval_ms) {
                                ^~~~~~~~
                                is_function
/data1/asherzhou/confluo-single-machine/libconfluo/src/threads/periodic_task.cc:25:41: error: expected primary-expression before 'void'
 bool periodic_task::start(std::function<void(void)> task, uint64_t interval_ms) {
                                         ^~~~
/data1/asherzhou/confluo-single-machine/libconfluo/src/threads/periodic_task.cc:25:68: error: expected primary-expression before 'interval_ms'
 bool periodic_task::start(std::function<void(void)> task, uint64_t interval_ms) {
                                                                    ^~~~~~~~~~~
/data1/asherzhou/confluo-single-machine/libconfluo/src/threads/periodic_task.cc:25:79: error: expression list treated as compound expression in initializer [-fpermissive]
    
```
This issue can be solved by adding

`#include <functional>`

into /confluo-single-machine/libconfluo/confluo/threads/periodic_task.h

**Comment by anuragkh** [comment] 2018-12-31 07:03
Can you please provide the complete CMake and make logs? I’ll try to reproduce the issue and push a fix.

**Comment by asherzhou** [comment] 2019-01-02 07:55
OK,  The relevant documents have been sent to your mailbox, I do not know if you want.

**Comment by anuragkh** [comment] 2019-01-02 09:38
Great, thanks! I was able to reproduce the issue and have pushed a fix which adds the include statement. Can you confirm the the issue does not appear now?

**Comment by anuragkh** [comment] 2019-01-03 19:44
@asherzhou Were you able to confirm if this works now?

**Comment by anuragkh** [comment] 2019-01-15 03:07
@asherzhou Checking back on this.

**Comment by anuragkh** [comment] 2019-01-29 23:40
Closing this due to inactivity. Please re-open if the problem persists.

**Closed as completed by anuragkh** 2019-01-29 23:40 UTC
